import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { PlayCircle, BookOpen, Sparkles, Target, BarChart3, Plug, GitBranch, CheckCircle2, Clock } from "lucide-react";

export const Route = createFileRoute("/_authenticated/dashboard/academy")({
  head: () => ({ meta: [{ title: "Academy — Aurevia" }] }),
  component: Academy,
});

const MODULES = [
  {
    id: "start",
    icon: Sparkles,
    duration: "6 min",
    level: "Foundations",
    title: "Welcome to Aurevia",
    summary: "Understand the credit model, the 5 agents, and the workflow you'll use daily.",
    lessons: [
      "What is an AI marketing agent",
      "How credits work and how to top up",
      "The 5 agents in 60 seconds each",
    ],
  },
  {
    id: "integrations",
    icon: Plug,
    duration: "10 min",
    level: "Setup",
    title: "Connect Meta, Google & BidMachine",
    summary: "Grant OAuth access so agents can read metrics and launch campaigns on your behalf.",
    lessons: [
      "Connect Meta Ads (Business Manager)",
      "Connect Google Ads (MCC)",
      "Connect BidMachine programmatic",
      "Verify pixel & conversion API",
    ],
  },
  {
    id: "campaigns",
    icon: Target,
    duration: "14 min",
    level: "Operate",
    title: "Launch campaigns by prompt",
    summary: "Talk to the Ads Agent like a senior media buyer. Refine, deploy, monitor.",
    lessons: [
      "Anatomy of a great brief",
      "Audience prompts that work in EU",
      "Budget pacing & guardrails",
      "Approving creatives generated by Brand Agent",
    ],
  },
  {
    id: "funnels",
    icon: GitBranch,
    duration: "8 min",
    level: "Strategy",
    title: "Design your funnel boards",
    summary: "Create named funnels per project and let agents fill each stage with assets.",
    lessons: [
      "Create a funnel board",
      "Stages: Awareness → Consideration → Conversion",
      "Linking landing pages and Stripe checkouts",
    ],
  },
  {
    id: "reports",
    icon: BarChart3,
    duration: "5 min",
    level: "Insights",
    title: "Read the 3-hour pulse",
    summary: "Every 3 hours the Reports Agent posts a status update in your active chats.",
    lessons: [
      "Reading ROAS, CPL and CAC at a glance",
      "Asking follow-up questions",
      "Exporting executive briefings",
    ],
  },
];

function Academy() {
  const [done, setDone] = useState<Record<string, boolean>>({});
  const completed = Object.values(done).filter(Boolean).length;

  return (
    <div className="px-6 md:px-10 py-10 md:py-14 max-w-6xl">
      <div className="mb-10">
        <div className="flex items-center gap-2 text-[10px] uppercase tracking-widest text-neon mb-3">
          <BookOpen className="size-3" /> Academy
        </div>
        <h1 className="font-heading text-3xl md:text-4xl font-medium tracking-tight mb-3">
          Learn the platform in under an hour.
        </h1>
        <p className="text-sm md:text-base text-brand-muted max-w-2xl">
          Short, focused lessons so you can prompt your agents like a director — not a beginner.
          Mark modules as complete to track your progress.
        </p>

        <div className="mt-6 flex items-center gap-3">
          <div className="flex-1 max-w-xs h-1.5 rounded-full bg-brand-surface overflow-hidden">
            <div
              className="h-full bg-neon transition-all duration-500"
              style={{ width: `${(completed / MODULES.length) * 100}%`, boxShadow: "0 0 12px var(--neon)" }}
            />
          </div>
          <span className="text-xs text-brand-muted">{completed}/{MODULES.length} completed</span>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {MODULES.map((m) => {
          const Icon = m.icon;
          const isDone = !!done[m.id];
          return (
            <article
              key={m.id}
              className="group p-6 rounded-2xl bg-brand-surface ring-1 ring-brand-border hover:ring-neon/50 transition-all hover:shadow-[0_0_30px_-12px_var(--neon)]"
            >
              <div className="flex items-start justify-between mb-4">
                <div className="size-10 rounded-xl bg-brand-bg ring-1 ring-brand-border flex items-center justify-center group-hover:ring-neon/40 transition">
                  <Icon className="size-4 text-neon" />
                </div>
                <div className="flex items-center gap-3 text-[10px] uppercase tracking-widest text-brand-muted">
                  <span className="flex items-center gap-1"><Clock className="size-3" /> {m.duration}</span>
                  <span>{m.level}</span>
                </div>
              </div>
              <h3 className="font-heading text-lg font-medium tracking-tight mb-2">{m.title}</h3>
              <p className="text-sm text-brand-muted leading-relaxed mb-4">{m.summary}</p>
              <ul className="space-y-2 mb-5">
                {m.lessons.map((l) => (
                  <li key={l} className="flex items-start gap-2 text-xs text-brand-muted">
                    <span className="mt-1 size-1 rounded-full bg-neon shrink-0 shadow-[0_0_6px_var(--neon)]" />
                    {l}
                  </li>
                ))}
              </ul>
              <div className="flex items-center gap-2">
                <button className="btn-neon text-xs px-3 py-1.5 inline-flex items-center gap-1.5">
                  <PlayCircle className="size-3.5" /> Start module
                </button>
                <button
                  onClick={() => setDone((d) => ({ ...d, [m.id]: !d[m.id] }))}
                  className={
                    "text-xs px-3 py-1.5 rounded-md inline-flex items-center gap-1.5 transition " +
                    (isDone ? "bg-neon/15 text-neon ring-1 ring-neon/50" : "btn-dark")
                  }
                >
                  <CheckCircle2 className="size-3.5" /> {isDone ? "Completed" : "Mark complete"}
                </button>
              </div>
            </article>
          );
        })}
      </div>
    </div>
  );
}
