/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardIntegrationsRouteImport } from './routes/_authenticated/dashboard.integrations'
import { Route as AuthenticatedDashboardFunnelRouteImport } from './routes/_authenticated/dashboard.funnel'
import { Route as AuthenticatedDashboardChatRouteImport } from './routes/_authenticated/dashboard.chat'
import { Route as AuthenticatedDashboardBillingRouteImport } from './routes/_authenticated/dashboard.billing'
import { Route as AuthenticatedDashboardAcademyRouteImport } from './routes/_authenticated/dashboard.academy'
import { Route as AuthenticatedDashboardAgentsSlugRouteImport } from './routes/_authenticated/dashboard.agents.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIntegrationsRoute =
  AuthenticatedDashboardIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFunnelRoute =
  AuthenticatedDashboardFunnelRouteImport.update({
    id: '/funnel',
    path: '/funnel',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardChatRoute =
  AuthenticatedDashboardChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBillingRoute =
  AuthenticatedDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAcademyRoute =
  AuthenticatedDashboardAcademyRouteImport.update({
    id: '/academy',
    path: '/academy',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAgentsSlugRoute =
  AuthenticatedDashboardAgentsSlugRouteImport.update({
    id: '/agents/$slug',
    path: '/agents/$slug',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/academy': typeof AuthenticatedDashboardAcademyRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/chat': typeof AuthenticatedDashboardChatRoute
  '/dashboard/funnel': typeof AuthenticatedDashboardFunnelRoute
  '/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/agents/$slug': typeof AuthenticatedDashboardAgentsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/academy': typeof AuthenticatedDashboardAcademyRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/chat': typeof AuthenticatedDashboardChatRoute
  '/dashboard/funnel': typeof AuthenticatedDashboardFunnelRoute
  '/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/agents/$slug': typeof AuthenticatedDashboardAgentsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/academy': typeof AuthenticatedDashboardAcademyRoute
  '/_authenticated/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/_authenticated/dashboard/chat': typeof AuthenticatedDashboardChatRoute
  '/_authenticated/dashboard/funnel': typeof AuthenticatedDashboardFunnelRoute
  '/_authenticated/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/agents/$slug': typeof AuthenticatedDashboardAgentsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/academy'
    | '/dashboard/billing'
    | '/dashboard/chat'
    | '/dashboard/funnel'
    | '/dashboard/integrations'
    | '/dashboard/'
    | '/dashboard/agents/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/academy'
    | '/dashboard/billing'
    | '/dashboard/chat'
    | '/dashboard/funnel'
    | '/dashboard/integrations'
    | '/dashboard'
    | '/dashboard/agents/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/academy'
    | '/_authenticated/dashboard/billing'
    | '/_authenticated/dashboard/chat'
    | '/_authenticated/dashboard/funnel'
    | '/_authenticated/dashboard/integrations'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/agents/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/integrations': {
      id: '/_authenticated/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof AuthenticatedDashboardIntegrationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/funnel': {
      id: '/_authenticated/dashboard/funnel'
      path: '/funnel'
      fullPath: '/dashboard/funnel'
      preLoaderRoute: typeof AuthenticatedDashboardFunnelRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/chat': {
      id: '/_authenticated/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof AuthenticatedDashboardChatRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/billing': {
      id: '/_authenticated/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthenticatedDashboardBillingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/academy': {
      id: '/_authenticated/dashboard/academy'
      path: '/academy'
      fullPath: '/dashboard/academy'
      preLoaderRoute: typeof AuthenticatedDashboardAcademyRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/agents/$slug': {
      id: '/_authenticated/dashboard/agents/$slug'
      path: '/agents/$slug'
      fullPath: '/dashboard/agents/$slug'
      preLoaderRoute: typeof AuthenticatedDashboardAgentsSlugRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAcademyRoute: typeof AuthenticatedDashboardAcademyRoute
  AuthenticatedDashboardBillingRoute: typeof AuthenticatedDashboardBillingRoute
  AuthenticatedDashboardChatRoute: typeof AuthenticatedDashboardChatRoute
  AuthenticatedDashboardFunnelRoute: typeof AuthenticatedDashboardFunnelRoute
  AuthenticatedDashboardIntegrationsRoute: typeof AuthenticatedDashboardIntegrationsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardAgentsSlugRoute: typeof AuthenticatedDashboardAgentsSlugRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAcademyRoute: AuthenticatedDashboardAcademyRoute,
    AuthenticatedDashboardBillingRoute: AuthenticatedDashboardBillingRoute,
    AuthenticatedDashboardChatRoute: AuthenticatedDashboardChatRoute,
    AuthenticatedDashboardFunnelRoute: AuthenticatedDashboardFunnelRoute,
    AuthenticatedDashboardIntegrationsRoute:
      AuthenticatedDashboardIntegrationsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardAgentsSlugRoute:
      AuthenticatedDashboardAgentsSlugRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
